name: Formatting

on:
  push:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/fmt.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/fmt.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-08-19
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
